### ISSUE TITLE
Allow users to select between PDB2PQR versions

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-web#2] opened 2020-12-22 22:59 UTC
Alluded to [here](https://github.com/Electrostatics/pdb2pqr/issues/129#issuecomment-749804301), we'd need to add options on the PDB2PQR configuration page to **switch between PDB2PQR versions 2.1.1 and 3.1.0** (latest)

- This can be in the form of a dropdown.
- Adjust additional options based on version (e.g. removing PDB2PKA fields when PDB2PQR 3 is selected)

**Comment by intendo** [comment] 2021-03-23 17:47
@sobolevnrm do you think version 3.1.0 is stable enough that we should just support it and drop version 2.1.1?
The reason I ask is that 2.1.1 requires Python 2.7 and I was trying to get us to strictly 3.X to make maintenance and deployments easier.
Is there anything in 2.1.1 that got dropped moving to 3.1.0?
Were there things added to 3.1.0 that @Eo300 would have to add features or GUI elements to support it?

**Comment by sobolevnrm** [comment] 2021-03-24 12:49
> @sobolevnrm do you think version 3.1.0 is stable enough that we should just support it and drop version 2.1.1?
> The reason I ask is that 2.1.1 requires Python 2.7 and I was trying to get us to strictly 3.X to make maintenance and deployments easier.
> Is there anything in 2.1.1 that got dropped moving to 3.1.0?
> Were there things added to 3.1.0 that @Eo300 would have to add features or GUI elements to support it?

I think we should drop it soon but *after* we've confirmed that the AWS deployment works the same way as the current Azure deployment.  

The change will require removal of the PDB2PKA radio button on the PDB2PQR web form.

**Comment by intendo** [comment] 2021-05-21 16:37
The PDB2PKA option was removed as part of #26 

@sobolevnrm now that we have PDB2PQR 2.1.1 working correctly on AWS, I think we could swap it out for version 3.1.0.
From the release notes of 3.1.0, I don't think there is anything we would have to change on the existing web interface (e.g., adding new options). 

Do we need to support things like psize or dxcube command line options from the web interface?

If not, do you know of any changes that we would need to make to support version 3.1.0?

**Comment by sobolevnrm** [comment] 2021-05-22 14:38
Sounds good to me.  Didn't we drop PDB2PKA in 3.*?  That would require a web interface change.

**Comment by Eo300** [comment] 2021-05-24 19:13
Due to Electrostatics/apbs-aws#62, we removed the PDB2PKA option from the interface already.  So we could try swapping in PDB2PQR 3 if the CLI is consistent (w/ the exception of PDB2PKA)

**Comment by intendo** [comment] 2021-07-27 20:28
We dropped PDB2PQR 2.X so this is no longer needed.

**Closed by intendo** 2021-07-27 20:28 UTC
